### ISSUE TITLE
Cannot see Python mode in Processing 3.3.6 on Mac OS 10.11.6

### ISSUE THREAD

**Issue by Vit1leman** [jdf/Processing.py-Bugs#198]
I don't see Python mode available for the download in Processing 3.3.6 Contributions Manager. Am i missing some step or it is not available on Mac ?

**Comment by jdf** [comment]
Augh! There was a permissions problem on the distribution. I've fixed it, and hope that the mode will reappear in the contributions manager either now or after the next processing update manager refresh, whenever that is. So sorry, and thanks for the report!

**Comment by Vit1leman** [comment]
Thanks for the quick answer. The Python mode is still not visible in Processing - is there a way to copy / install it manually somehow meanwhile ? Much appreciated!

**Comment by jdf** [comment]
I'm sorry for the trouble. It should appear in the contributions manager again soon. Until it does, you should be able to download http://py.processing.org/3/PythonMode.zip and unzip it into the "modes" directory of your Processing "sketchbook" folder (which is different for each platform).
